coverage:
  precision: 2
  round: down
  range: "75...90"
  status:
    project:
      default: false
      adsb:
        target: 90%
        paths:
          - adsb
      beast:
        target: 90%
        paths:
          - beast
      adsbtype:
        target: 90%
        paths:
          - adsbtype
    patch:
      default:
        target: auto
        threshold: 10%
